title: DevOpsDay2018
url: https://reaton333.github.io/demo-dev-ops-day # the base hostname & protocol for your site
baseurl: /demo-dev-ops-day/ # the subpath of your site, e.g. /blog


logo: "../css/2016_style/img/icon-large.png"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

permalink:           pretty
relative_permalinks: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
# markdown: kramdown
# permalink: pretty
