title: DevOpsDay2018
description: > # this means to ignore newlines until "baseurl:"
  Your description
url: http://reaton333.github.io/demo-dev-ops-day # the base hostname & protocol for your site
baseurl: /demo-dev-ops-day/ # the subpath of your site, e.g. /blog


sass:
  sass_dir:          _sass/2016_sass
  style:            :compressed

logo: "../css/2016_style/img/icon-large.png"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: pretty
